language: c

dist: bionic

env:
  matrix:
    - FEDORA_KIND="releases" FEDORA_MAJOR="32"
    - FEDORA_KIND="development" FEDORA_MAJOR="rawhide"

addons:
  apt:
    packages:
      - grubby
      - astyle
      - qemu-kvm
      - libvirt-bin
      - virtinst
      - bridge-utils
      - libguestfs-tools
      - cpu-checker

before_install:
  # FYI: known good with HEAD at 8551fc60fc515cd290ba38ee8c758c1f4df52b56
  - git clone https://github.com/perltidy/perltidy.git perltidy
  - |
    (cd perltidy &&
     perl Makefile.PL &&
     make PREFIX=/usr/local &&
     sudo make install PREFIX=/usr/local)
  - sudo usermod -a -G kvm,libvirt,libvirt-qemu "$USER"
  # Verify that KVM is working, useful if Travis ever changes anything.
  - kvm-ok
  - sudo systemctl enable libvirtd
  - sudo systemctl start libvirtd
  # Set up a key so we can ssh into the VM
  - ssh-keygen -N "" -f "$HOME/.ssh/id_rsa"

script:
  - tools/check-syntax -f && git diff --exit-code
  - bash travis-ci/run-kvm-test.sh travis-ci/run-testsuite.sh
