#!/bin/sh

netlabelctl map del default
netlabelctl map add default address:0.0.0.0/0 protocol:unlbl
netlabelctl unlbl add interface:lo address:127.0.0.0/8 label:system_u:object_r:netlabel_sctp_peer_t:s0
if test -f /proc/net/if_inet6; then
	netlabelctl map add default address:::/0 protocol:unlbl
	netlabelctl unlbl add interface:lo address:::1/128 label:system_u:object_r:netlabel_sctp_peer_t:s0
fi
#netlabelctl -p unlbl list
