#!/usr/bin/perl
use Test::More;

#
# These tests cover the net/sctp security hooks as discussed in kernel tree:
#     Documentation/security/SCTP.rst
# The only two places in SCTP code not tested as they need unusual sctp
# packets to be sent are:
#   net/sctp/sm_statefuns.c sctp_sf_do_unexpected_init - assoc_request
#   net/sctp/sm_statefuns.c sctp_sf_do_5_2_4_dupcook - assoc_request
#
# Network traffic can be followed using tshark(1):
#        tshark -O sctp,ipv6,ip,cipso,calipso -P -x -i any
#

BEGIN {
    $N = 20;

    $basedir = $0;
    $basedir =~ s|(.*)/[^/]*|$1|;

    # allow SCTP info to be shown during tests
    $v = $ARGV[0];
    if ($v) {
        if ( $v ne "-v" ) {
            plan skip_all => "Invalid option (use -v)";
        }
    }
    else {
        $v = " ";
    }

    # check if SCTP is enabled
    if ( system("modprobe sctp 2>/dev/null && checksctp 2>/dev/null") != 0 ) {
        plan skip_all => "SCTP not supported";
    }
    else {
        $test_count = 67;

        # Set up a GRE tunnel over loopback to ensure we have enough addresses
        # for the ASCONF tests.
        system "ip link add mygre type gretap local 127.0.0.1 remote 127.0.0.1";
        system "ip addr add 10.123.123.123 dev mygre";
        system "ip link set mygre up";

        # asconf parameter tests require two local non-loopback addresses.
        $ipaddress_list = `ip -o addr show up scope global`;
        $test_asconf    = 0;
        $test_clpeeloff = 0;
        $count          = 0;
        $ipaddress[0]   = 0;
        $ipaddress[1]   = 0;

        for my $line ( split /\n/, $ipaddress_list ) {
            if ( $line =~ /inet ([^ \/]+)/ && $count < 2 ) {
                $ipaddress[$count] = $1;
                $count++;
            }
        }

        if ( $ipaddress[1] ne 0 and $ipaddress[0] ne $ipaddress[1] ) {
            $test_count += 3;
            $test_asconf = 1;
        }

        # SCTP client peeloff has been fixed in kernel 5.18+
        $kvercur = `uname -r`;
        chomp($kvercur);

        if ( `$basedir/../kvercmp $kvercur 5.18` > 0 ) {
            $test_clpeeloff = 1;
            $test_count += 18;
        }

        # Determine if CALIPSO supported by netlabelctl(8) and kernel.
        $test_calipso = 0;
        $netlabelctl  = `netlabelctl -V`;
        $netlabelctl =~ s/\D//g;

        $rc = `$basedir/../kvercmp $kvercur 4.8`;
        if ( $netlabelctl gt "021" && $rc > 0 ) {
            $test_count += 13;
            if ($test_clpeeloff) {
                $test_count += 6;
            }
            $test_calipso = 1;
        }

        # Determine if kernel has legacy iptables support
        $test_iptables = 0;

        $rc = system("modprobe ip_tables 2>/dev/null");
        if ( $rc == 0 ) {
            $test_count += 8;
            $test_iptables = 1;
        }

        # Determine if nftables has secmark support
        $test_nft = 0;

        $rc = system("nft -c -f $basedir/nftables-load 2>/dev/null");
        if ( $rc == 0 ) {
            $test_count += 8;
            $test_nft = 1;
        }
    }

    plan tests => 3*$N;
}

sub server_start {
    my ( $runcon_args, $prog, $args ) = @_;
    my $pid;

    system("mkfifo $basedir/flag");

    if ( ( $pid = fork() ) == 0 ) {
        exec "runcon $runcon_args $basedir/$prog -f $basedir/flag $args";
    }

    # Wait for it to initialize.
    system("read -t 5 <>$basedir/flag");
    return $pid;
}

sub server_end {
    my ($pid) = @_;

    kill KILL, $pid;
    waitpid $pid, 0;
    system("rm -f $basedir/flag");
}

#
##################### Dynamic Address Reconfiguration #####################
#
# These tests require two non-loopback addresses.
#
# Server - setsockopt(SCTP_SET_PEER_PRIMARY_ADDR, $ipaddress[0]);
# net/sctp/sm_make_chunk.c sctp_process_asconf_param() SCTP_PARAM_SET_PRIMARY
# Server -> Client (Set $ipaddress[0] as primary - client acks)
#
# Server - sctp_bindx(SCTP_BINDX_ADD_ADDR, $ipaddress[1]);
# net/sctp/sm_make_chunk.c sctp_process_asconf_param() SCTP_PARAM_ADD_IP
# Server -> Client (Set $ipaddress[1] as primary - client acks)
#
# These are sent by the server and require bind permission. They are
# received by the client and the SCTP_PARAM_ADD_IP is validated when
# $ipaddress[1] is set for use via:
#    net/sctp/socket.c sctp_setsockopt_peer_primary_addr(setsockopt(SCTP_PRIMARY_ADDR))
# This requires the 'bind' permission, if not granted client exits with 51.
#

for (1..$N) {

    # To enable processing of ASCONF parameters SCTP_PARAM_SET_PRIMARY
    # and SCTP_PARAM_ADD_IP need to set:
    system("echo 1 > /proc/sys/net/sctp/addip_enable");
    system("echo 1 > /proc/sys/net/sctp/addip_noauth_enable");

    print "Testing Dynamic Address Reconfiguration\n";

    # Server should automatically exit after each test
    $pid = server_start(
        "-t sctp_asconf_params_server_t",
        "sctp_asconf_params_server",
        "$v $ipaddress[0] $ipaddress[1] 1035"
    );

    $result = system
"runcon -t sctp_asconf_params_client_t $basedir/sctp_asconf_params_client $v $ipaddress[0] 1035";
    ok( $result eq 0 );

    server_end($pid);

    $pid = server_start(
        "-t sctp_asconf_params_server_t",
        "sctp_asconf_params_server",
        "$v $ipaddress[0] $ipaddress[1] 1035"
    );

    print "Testing deny SCTP_PRIMARY_ADDR\n";
    $result = system
"runcon -t sctp_asconf_deny_pri_addr_client_t $basedir/sctp_asconf_params_client $v $ipaddress[0] 1035 2>&1";
    ok( $result >> 8 eq 51 );    # setsockopt(2) failed

    server_end($pid);

    #
    # This is a local only test as it's the neverallow rule that stops:
    #    server -> client sctp_socket { connect };
    #
    # Srv sends SCTP_PARAM_ADD_IP and SCTP_PARAM_SET_PRIMARY in ASCONF's
    # Client returns ASCONF_ACK's with 'Request refused - no authorization'
    $pid = server_start(
        "-t sctp_asconf_params_server_t",
        "sctp_asconf_params_server",
        "$v $ipaddress[0] $ipaddress[1] 1035"
    );

    print "Testing deny SCTP_PARAM_ADD_IP/SCTP_PARAM_SET_PRIMARY\n";
    $result = system
"runcon -t sctp_asconf_deny_param_add_client_t $basedir/sctp_asconf_params_client $v $ipaddress[0] 1035 2>&1";
    ok( $result >> 8 eq 52 );

    server_end($pid);

    system("echo 0 > /proc/sys/net/sctp/addip_enable");
    system("echo 0 > /proc/sys/net/sctp/addip_noauth_enable");
}

system "ip link del mygre";

exit;
