name: checks
on: [push, pull_request]
jobs:
  fedora-rawhide:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      # macOS sometimes allows symlinks to have permissions other than 777,
      # so change all symlink perms to match the Linux convention. Otherwise
      # the rsync run by Vagrant will complain that it can't copy over the
      # perms.
      - name: Fix symlink permissions
        run: find . -type link -exec chmod -h 777 \{\} \;
      - name: Create a Vagrant VM
        run: |
          image="$(.github/workflows/download-rawhide-image.sh /tmp)"
          vagrant box add rawhide "file://$image"
          IMAGE_NAME=rawhide vagrant up
      - name: lscpu
        run: vagrant ssh -- lscpu
      - name: Run SELinux testsuite
        run: vagrant ssh -- sudo make -C /root/testsuite test
