name: checks
on: [push, pull_request]
jobs:
  style-check:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - run: sudo dnf install -y astyle perltidy findutils git-core
      - uses: actions/checkout@v2
      - run: tools/check-syntax -f && git diff --exit-code
  fedora-test:
    runs-on: macos-latest
    strategy:
      matrix:
        env:
          - { version: 33, secnext: 0 }
          - { version: 33, secnext: 1 }
    env:
      FEDORA_VERSION: ${{ matrix.env.version }}
      KERNEL_SECNEXT: ${{ matrix.env.secnext }}
    steps:
      - uses: actions/checkout@v2
      # macOS sometimes allows symlinks to have permissions other than 777,
      # so change all symlink perms to match the Linux convention. Otherwise
      # the rsync run by Vagrant will complain that it can't copy over the
      # perms.
      - name: Fix symlink permissions
        run: find . -type link -exec chmod -h 777 \{\} \;
      - name: Create a Vagrant VM
        run: vagrant up
      - name: Clear audit log
        run: vagrant ssh -- sudo tee /var/log/audit/audit.log </dev/null
      - name: Load testsuite policy
        run: vagrant ssh -- sudo make -C /root/testsuite/policy load
      #- name: Run SELinux testsuite
      #  run: vagrant ssh -- sudo make -C /root/testsuite/tests test
      - name: Run NFS test
        run: vagrant ssh -- sudo env -C /root/testsuite ./tools/nfs.sh nfs_filesystem
        continue-on-error: true
      - name: Show AVC records
        run: vagrant ssh -- sudo ausearch -i -m AVC
      - name: Unload testsuite policy
        run: vagrant ssh -- sudo make -C /root/testsuite/policy unload
